# Generated by Django 5.2.11 on 2026-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_crop",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
